apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-partners-consolidation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-partners-consolidation
  template:
    metadata:
      labels:
        app: projects-partners-consolidation
    spec:
      containers:
        - name: app
          image: projects-partners-consolidation:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: projects-partners-service
spec:
  selector:
    app: projects-partners-consolidation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
